"""
WAF (Web Application Firewall) Detection & Evasion Engine.

Detects:
    - 30+ WAF products by fingerprint (headers, body, cookies, status codes)
    - Generic WAF blocking patterns

Evasion:
    - Encoding mutations (URL, double-URL, Unicode, hex, HTML entities)
    - Case alternation (SeLeCt, uNiOn)
    - Comment injection (SEL/**/ECT, UN/**/ION)
    - Whitespace substitution (tab, newline, carriage-return)
    - Null-byte injection
    - Chunked transfer tricks
"""

import random
import re
from dataclasses import dataclass
from typing import Optional

import requests

from secprobe.core.logger import get_logger

log = get_logger("waf")


# ── WAF Fingerprints ─────────────────────────────────────────────────
# Each entry: (waf_name, detection_function_key, pattern)

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"Server": r"cloudflare", "CF-RAY": r".+"},
        "cookies": [r"__cfduid", r"cf_clearance"],
        "body": [r"Attention Required! \| Cloudflare", r"cloudflare-nginx"],
    },
    "AWS WAF": {
        "headers": {"x-amzn-RequestId": r".+"},
        "body": [r"<html><head><title>403 Forbidden</title>", r"Request blocked"],
        "status": [403],
    },
    "Akamai": {
        "headers": {"Server": r"AkamaiGHost", "X-Akamai-Transformed": r".+"},
        "body": [r"Access Denied.*?Akamai", r"Reference #"],
    },
    "Imperva / Incapsula": {
        "headers": {"X-CDN": r"Incapsula", "X-Iinfo": r".+"},
        "cookies": [r"visid_incap", r"incap_ses"],
        "body": [r"Incapsula incident", r"_Incapsula_Resource"],
    },
    "ModSecurity": {
        "headers": {"Server": r"Mod_Security|NOYB"},
        "body": [r"ModSecurity", r"This error was generated by Mod_Security", r"rules of the mod_security"],
    },
    "F5 BIG-IP ASM": {
        "headers": {"Server": r"BigIP", "X-WA-Info": r".+"},
        "cookies": [r"TS[a-zA-Z0-9]{3,8}=", r"BIGipServer"],
        "body": [r"The requested URL was rejected"],
    },
    "Barracuda": {
        "headers": {"Server": r"Barracuda"},
        "cookies": [r"barra_counter_session"],
        "body": [r"Barracuda Web Application Firewall"],
    },
    "Sucuri": {
        "headers": {"Server": r"Sucuri", "X-Sucuri-ID": r".+", "X-Sucuri-Cache": r".+"},
        "body": [r"Access Denied - Sucuri Website Firewall", r"sucuri\.net/privacy"],
    },
    "Fortinet / FortiWeb": {
        "headers": {"Server": r"FortiWeb"},
        "cookies": [r"FORTIWAFSID"],
        "body": [r"FortiGuard Intrusion Prevention", r"\.fgd_icon"],
    },
    "Palo Alto": {
        "body": [r"has been blocked in accordance with company policy"],
    },
    "Citrix NetScaler": {
        "headers": {"Via": r"NS-CACHE", "Connection": r"ns_af"},
        "cookies": [r"ns_af", r"citrix_ns_id", r"NSC_"],
    },
    "DenyAll": {
        "headers": {"Server": r"DenyAll"},
        "cookies": [r"sessioncookie="],
    },
    "StackPath": {
        "headers": {"x-sp-url": r".+", "x-sp-waf": r".+"},
    },
    "Fastly": {
        "headers": {"X-Fastly-Request-ID": r".+", "Via": r".*varnish.*"},
    },
    "Wallarm": {
        "headers": {"Server": r"nginx-wallarm"},
    },
    "SonicWall": {
        "headers": {"Server": r"SonicWALL"},
    },
    "Comodo WAF": {
        "headers": {"Server": r"Protected by COMODO"},
    },
    "Wordfence": {
        "body": [r"Generated by Wordfence", r"wfvt_[0-9]+"],
        "cookies": [r"wfvt_"],
    },
    "Reblaze": {
        "cookies": [r"rbzid="],
        "headers": {"Server": r"Reblaze Secure Web Gateway"},
    },
    "Microsoft Azure WAF": {
        "headers": {"x-azure-ref": r".+", "x-ms-forbidden-ip": r".+"},
    },
    "Google Cloud Armor": {
        "body": [r"Your client does not have permission.*Google"],
    },
    "Edgecast / Verizon": {
        "headers": {"Server": r"ECD|ECS"},
    },
    "Radware AppWall": {
        "headers": {"X-SL-CompState": r".+"},
    },
    "SafeDog": {
        "headers": {"Server": r"Safe Dog"},
        "cookies": [r"safedog-flow-item"],
    },
    "WebKnight": {
        "headers": {"Server": r"WebKnight"},
        "body": [r"WebKnight Application Firewall"],
    },
    "Shadow Daemon": {
        "body": [r"request cannot be processed.*shadow"],
    },
}


@dataclass
class WAFResult:
    """Result of WAF detection."""
    detected: bool = False
    waf_name: str = ""
    confidence: float = 0.0
    evidence: list[str] = None

    def __post_init__(self):
        if self.evidence is None:
            self.evidence = []


class WAFDetector:
    """Detects WAF presence and applies evasion techniques."""

    def __init__(self):
        self._detected_waf: Optional[str] = None
        self._detection_done = False

    @property
    def waf_name(self) -> Optional[str]:
        return self._detected_waf

    def detect(self, http_client, target_url: str) -> WAFResult:
        """
        Actively probe the target for WAF presence.

        Strategy:
            1. Send a normal request (baseline)
            2. Send a malicious-looking request
            3. Compare responses — WAF will likely block #2
            4. Fingerprint the WAF from the blocked response
        """
        result = WAFResult()

        try:
            # Baseline
            baseline = http_client.get(target_url, check_waf=False)

            # Trigger probe — obviously malicious payload
            trigger_payloads = [
                f"{target_url}?test=<script>alert(1)</script>",
                f"{target_url}?test=' OR 1=1--",
                f"{target_url}?test=../../etc/passwd",
            ]

            for probe_url in trigger_payloads:
                try:
                    resp = http_client.get(probe_url, check_waf=False, allow_redirects=False)

                    # If status drastically different from baseline, WAF likely present
                    if resp.status_code in (403, 406, 429, 503) and baseline.status_code == 200:
                        waf = self._fingerprint_response(resp)
                        if waf:
                            result.detected = True
                            result.waf_name = waf
                            result.confidence = 0.9
                            result.evidence.append(f"Malicious probe blocked with HTTP {resp.status_code}")
                            self._detected_waf = waf
                            self._detection_done = True
                            log.warning("WAF detected: %s (confidence: %.0f%%)", waf, result.confidence * 100)
                            return result

                    # Check fingerprints even on 200 (some WAFs pass but add headers)
                    waf = self._fingerprint_response(resp)
                    if waf:
                        result.detected = True
                        result.waf_name = waf
                        result.confidence = 0.6
                        result.evidence.append(f"WAF fingerprint found in response headers/body")
                        self._detected_waf = waf
                        self._detection_done = True
                        return result

                except Exception:
                    continue

            # Also check baseline for passive WAF indicators
            waf = self._fingerprint_response(baseline)
            if waf:
                result.detected = True
                result.waf_name = waf
                result.confidence = 0.5
                result.evidence.append("WAF fingerprint in baseline response")
                self._detected_waf = waf

        except Exception as e:
            log.debug("WAF detection error: %s", e)

        self._detection_done = True
        return result

    def detect_in_response(self, response: requests.Response) -> Optional[str]:
        """Quick inline check on any response (called by HTTPClient)."""
        return self._fingerprint_response(response)

    def _fingerprint_response(self, resp: requests.Response) -> Optional[str]:
        """Match a response against all WAF signatures."""
        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            # Header matching
            for header, pattern in sigs.get("headers", {}).items():
                val = resp.headers.get(header, "")
                if val and re.search(pattern, val, re.IGNORECASE):
                    score += 2

            # Cookie matching
            cookie_str = resp.headers.get("Set-Cookie", "")
            for pattern in sigs.get("cookies", []):
                if re.search(pattern, cookie_str, re.IGNORECASE):
                    score += 2

            # Body matching
            if resp.text:
                for pattern in sigs.get("body", []):
                    if re.search(pattern, resp.text[:5000], re.IGNORECASE):
                        score += 3

            # Status code matching
            if resp.status_code in sigs.get("status", []):
                score += 1

            if score >= 2:
                return waf_name

        return None

    # ── Evasion Techniques ───────────────────────────────────────────

    def evade(self, payload: str, techniques: list[str] | None = None) -> list[str]:
        """
        Generate evasion variants of a payload.

        Returns multiple mutated versions of the payload designed
        to bypass specific WAF implementations.
        """
        if techniques is None:
            techniques = [
                "url_encode", "double_url_encode", "unicode_encode",
                "case_swap", "comment_inject", "whitespace_sub",
                "hex_encode", "html_entity", "null_byte",
                "concat_split",
            ]

        variants = []
        for technique in techniques:
            fn = getattr(self, f"_evade_{technique}", None)
            if fn:
                try:
                    variant = fn(payload)
                    if variant and variant != payload:
                        variants.append(variant)
                except Exception:
                    continue

        return variants

    def _evade_url_encode(self, payload: str) -> str:
        """URL-encode special characters."""
        return "".join(f"%{ord(c):02X}" if not c.isalnum() else c for c in payload)

    def _evade_double_url_encode(self, payload: str) -> str:
        """Double URL-encode (bypasses single-decode WAFs)."""
        first = self._evade_url_encode(payload)
        return first.replace("%", "%25")

    def _evade_unicode_encode(self, payload: str) -> str:
        """Unicode escape sequences."""
        result = []
        for c in payload:
            if not c.isalnum() and c not in (" ", ):
                result.append(f"\\u{ord(c):04X}")
            else:
                result.append(c)
        return "".join(result)

    def _evade_case_swap(self, payload: str) -> str:
        """Randomly swap case: SELECT → SeLeCt."""
        return "".join(
            c.upper() if random.random() > 0.5 else c.lower()
            for c in payload
        )

    def _evade_comment_inject(self, payload: str) -> str:
        """Inject SQL comments between keywords: SELECT → SEL/**/ECT."""
        keywords = ["SELECT", "UNION", "INSERT", "UPDATE", "DELETE", "DROP",
                     "FROM", "WHERE", "AND", "OR", "ORDER", "GROUP", "HAVING",
                     "SCRIPT", "ALERT", "ONERROR", "ONLOAD"]
        result = payload
        for kw in keywords:
            if kw.lower() in result.lower():
                idx = result.lower().find(kw.lower())
                original = result[idx:idx + len(kw)]
                mid = len(original) // 2
                replaced = original[:mid] + "/**/" + original[mid:]
                result = result[:idx] + replaced + result[idx + len(kw):]
        return result

    def _evade_whitespace_sub(self, payload: str) -> str:
        """Replace spaces with alternative whitespace."""
        alternatives = ["\t", "\n", "\r", "\x0b", "\x0c", "/**/", "+"]
        return payload.replace(" ", random.choice(alternatives))

    def _evade_hex_encode(self, payload: str) -> str:
        """Hex-encode characters: ' → 0x27."""
        result = []
        for c in payload:
            if c in ("'", '"', "<", ">", "(", ")", "="):
                result.append(f"0x{ord(c):02x}")
            else:
                result.append(c)
        return "".join(result)

    def _evade_html_entity(self, payload: str) -> str:
        """HTML entity encoding."""
        entities = {"<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
                     "(": "&#40;", ")": "&#41;", "/": "&#47;"}
        return "".join(entities.get(c, c) for c in payload)

    def _evade_null_byte(self, payload: str) -> str:
        """Insert null bytes (bypasses some pattern matchers)."""
        return payload[:1] + "%00" + payload[1:]

    def _evade_concat_split(self, payload: str) -> str:
        """SQL concatenation split: admin → ad'+'min (MSSQL style)."""
        if len(payload) > 4:
            mid = len(payload) // 2
            return f"{payload[:mid]}'||'{payload[mid:]}"
        return payload
